server:
  port: ${AI_SERVICE_PORT}

spring:
  application:
    name: ai-service
  config:
    import: "configserver:${CONFIG_SERVER_URL}"
  profiles:
    active: local

  datasource:
    url: ${AI_DB_URL}
    username: ${AI_DB_USERNAME}
    password: ${AI_DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
