server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hub/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/auth/**
            - Path=/v1/users/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/v1/ai/**

jwt:
  secret: "my-super-secret-key-my-super-secret-key-1234"
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: refresh