server:
  port: ${ORDER_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    openfeign:
      client:
        config:
          delivery-service:
            url:

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true