server:
  port: ${USER_SERVICE_PORT:9006}

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
